// <auto-generated />
using System;
using EchoPlay.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EchoPlay.Data.Migrations
{
    [DbContext(typeof(EchoPlayDbContext))]
    [Migration("20260403113756_AddClearCacheOnNextStart")]
    partial class AddClearCacheOnNextStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.CachedNewRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.HasIndex("SeriesId", "ReleaseDate");

                    b.ToTable("CachedNewReleases", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.CoverImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasMaxLength(5242880)
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique();

                    b.HasIndex("EntityType", "LastChecked");

                    b.HasIndex("IsDeleted", "DeletedAt")
                        .HasFilter("IsDeleted = 1");

                    b.ToTable("CoverImages", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CoverLastChecked")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("LocalCoverData")
                        .HasMaxLength(5242880)
                        .HasColumnType("BLOB");

                    b.Property<string>("LocalFolderPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocalTrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackMatchKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "DeletedAt")
                        .HasFilter("IsDeleted = 1");

                    b.HasIndex("SeriesId", "EpisodeNumber");

                    b.HasIndex("SeriesId", "LocalFolderPath")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Episodes", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.LocalTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId", "TrackNumber");

                    b.HasIndex("IsDeleted", "DeletedAt")
                        .HasFilter("IsDeleted = 1");

                    b.ToTable("LocalTracks", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppleMusicArtistId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPattern")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnlineImported")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("LocalCoverData")
                        .HasMaxLength(5242880)
                        .HasColumnType("BLOB");

                    b.Property<string>("LocalFolderPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyArtistId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppleMusicArtistId")
                        .HasFilter("AppleMusicArtistId IS NOT NULL");

                    b.HasIndex("SpotifyArtistId")
                        .HasFilter("SpotifyArtistId IS NOT NULL");

                    b.HasIndex("Title");

                    b.HasIndex("IsDeleted", "DeletedAt")
                        .HasFilter("IsDeleted = 1");

                    b.HasIndex("IsFavorite", "Title")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IsOnlineImported", "Title")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IsSubscribed", "Title")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Playback.PlaybackState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("LastPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId")
                        .IsUnique();

                    b.HasIndex("IsCompleted", "EpisodeId")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IsDeleted", "DeletedAt")
                        .HasFilter("IsDeleted = 1");

                    b.ToTable("PlaybackStates", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Settings.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveProvider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveTheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoImportAfterScan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClearCacheOnNextStart")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DbPurgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpisodeFolderPattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAppStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOpenedPlayerFolder")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LocalLibraryEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalLibraryRootPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumLogLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewReleaseDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OfflineMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SaveCoverToDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Settings.DashboardPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Section", "Position")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SeriesId", "Section")
                        .IsUnique();

                    b.ToTable("DashboardPositions", (string)null);
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.CachedNewRelease", b =>
                {
                    b.HasOne("EchoPlay.Data.Entities.Library.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.Episode", b =>
                {
                    b.HasOne("EchoPlay.Data.Entities.Library.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Library.LocalTrack", b =>
                {
                    b.HasOne("EchoPlay.Data.Entities.Library.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Playback.PlaybackState", b =>
                {
                    b.HasOne("EchoPlay.Data.Entities.Library.Episode", "Episode")
                        .WithOne()
                        .HasForeignKey("EchoPlay.Data.Entities.Playback.PlaybackState", "EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("EchoPlay.Data.Entities.Settings.DashboardPosition", b =>
                {
                    b.HasOne("EchoPlay.Data.Entities.Library.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
